Bump prettier from 2.6.2 to 2.8.8
## Release notes

Sourced from prettier's releases.

2.8.8
This version is a republished version of v2.8.7.
A bad version was accidentally published and it can't be unpublished, apologies for the churn.
2.8.7

Allow multiple decorators on same getter/setter

🔗 Changelog
2.8.6

Allow decorators on private members and class expressions

🔗 Changelog
2.8.5

Support TypeScript 5.0

🔗 Changelog
2.8.4
🔗 Changelog
2.8.3
Support Angular 15.1
🔗 Changelog
2.8.2
🔗 Changelog
2.8.1
🔗 Changelog
2.8.0
diff
🔗 Release note
2.7.1
🔗 Changelog
2.7.0
diff
🔗 Release note

## Changelog

Sourced from prettier's changelog.

2.8.8
This version is a republished version of v2.8.7.
A bad version was accidentally published and it can't be unpublished, apologies for the churn.
2.8.7
diff
Allow multiple decorators on same getter/setter (#14584 by @​fisker)

// Input
class A {
 @decorator()
 get foo () {}
@​decorator()
set foo (value) {}
}
// Prettier 2.8.6
SyntaxError: Decorators cannot be applied to multiple get/set accessors of the same name. (5:3)
3 | get foo () {}
4 |
&gt; 5 | @​decorator()
| ^^^^^^^^^^^^
6 | set foo (value) {}
7 | }
// Prettier 2.8.7
class A {
@​decorator()
get foo() {}
@​decorator()
set foo(value) {}
}

2.8.6
diff
Allow decorators on private members and class expressions (#14548 by @​fisker)

// Input
&lt;/tr&gt;&lt;/table&gt;

... (truncated)

## Commits

1b7fad5 Release 2.8.8
543a9d7 Release 2.8.7
f9fae7f Allow multiple decorators on same getter/setter (#14584)
10fe1ed Release 2.8.6
44aef0b Allow decorator on private members and class expressions (#14548)
ddf3b43 Clean changelog
71ba29f Git blame ignore 2.8.5
c1808e8 Bump Prettier dependency to 2.8.5
0a79535 Release 2.8.5
019ebe5 Support TypeScript 5 (backport #14391 and #13819) (#14512)
Additional commits viewable in compare view

## Maintainer changes

This version was pushed to npm by prettier-bot, a new releaser for prettier since your current version.

![Dependabot compatibility score](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Issue-ID: CIMAN-33
Signed-off-by: dependabot[bot] <support@github.com>
Signed-off-by: onap.gh2gerrit <releng+onap-gh2gerrit@linuxfoundation.org>
Change-Id: I78e1ae95bf77412186b1f1495c09070a7bef2c3d
GitHub-PR: https://github.com/onap/portal-ng-ui/pull/139
GitHub-Hash: 9bbe89f13c450d25